lesson_4/blog_project/views/accounts.py
from flask import Blueprint, request, render_template, abort, url_for, redirect, flash
from flask_login import current_user, login_user, logout_user, login_required
from flask_mail import Mail, Message
from threading import Thread
from itsdangerous import URLSafeTimedSerializer
from werkzeug.security import generate_password_hash, check_password_hash

from lesson_4.blog_project import app
from lesson_4.blog_project.forms import SingUpForm, LoginForm, EditUserForm, ResetEmailForm, ResetPasswordForm
from lesson_4.blog_project.models import db, User, Blog

accounts_app = Blueprint('accounts_app', __name__)
mail = Mail(app)


def send_email_thread(msg):
    with app.app_context():
        mail.send(msg)


def send_email(subject, recipients, html_body):
    msg = Message(subject, recipients=recipients)
    msg.html = html_body
    thr = Thread(target=send_email_thread, args=[msg])
    thr.start()


def send_password_reset_link(user_email):
    password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    password_reset_url = url_for(
        'accounts_app.token_reset',
        token=password_reset_serializer.dumps(user_email, salt='password-reset-salt'),
        _external=True
    )

    html = render_template(
        'email_reset.html',
        password_reset_url=password_reset_url)

    send_email('Password Reset Requested', [user_email], html)


@accounts_app.route('/reset/', methods=['GET', 'POST'])
def reset_email():
    form = ResetEmailForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).one_or_none()
        if not user:
            flash('Invalid email address!', category='danger')
            return render_template('password_reset.html', form=form)
        else:
            send_password_reset_link(user.email)
            flash('Please check your email for a password reset link.', category='info')
        return redirect(url_for('accounts_app.login'))

    return render_template('password_reset.html', form=form)


@accounts_app.route('/reset/<token>', methods=['GET', 'POST'])
def token_reset(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = password_reset_serializer.loads(token, salt='password-reset-salt', max_age=3600)
    except:
        flash('The password reset link is invalid or has expired.', category='danger')
        return redirect(url_for('accounts_app.login'))

    form = ResetPasswordForm()

    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=email).first_or_404()
        except:
            flash('Invalid email address!', category='danger')
            return redirect(url_for('accounts_app.login'))

        new_password = form.password.data
        hash_and_salted_password = generate_password_hash(
            new_password,
            method='pbkdf2:sha256',
            salt_length=8,
        )
        user.password = hash_and_salted_password
        db.session.add(user)
        db.session.commit()

        logout_user()

        flash('Your password has been updated!', category='info')
        return redirect(url_for('accounts_app.login'))

    return render_template('reset_token_pass.html', token=token, form=form)


@accounts_app.route('/signup/', methods=['GET', 'POST'])
def signup():
    form = SingUpForm()
    if request.method == 'POST':
        username = form.username.data
        email = form.email.data

        user_by_username_exist = User.query.filter_by(username=username).one_or_none()
        user_by_email_exist = User.query.filter_by(email=email).one_or_none()

        if user_by_username_exist and user_by_email_exist:
            flash('This username is already taken. Try something else.', category='danger')
            flash('User with this email already exist. Try something else.', category='danger')
            return redirect(url_for('accounts_app.signup'))
        elif user_by_username_exist:
            flash('This username is already taken. Try something else.', category='danger')
            return redirect(url_for('accounts_app.signup'))
        elif user_by_email_exist:
            flash('User with this email already exist. Try something else.', category='danger')
            return redirect(url_for('accounts_app.signup'))
        else:
            password_1 = form.password_1.data
            password_2 = form.password_2.data
            if password_1 != password_2:
                flash('Passwords do not match! Try again', category='danger')
                return redirect(url_for('accounts_app.signup'))
            else:
                hash_and_salted_password = generate_password_hash(
                    password_1,
                    method='pbkdf2:sha256',
                    salt_length=8,
                )
                new_user = User(
                    username=username,
                    email=email,
                    password=hash_and_salted_password,
                )
                db.session.add(new_user)
                db.session.commit()

                flash('Your account has been successfully created! Login to continue.', category='info')

                return redirect(url_for('accounts_app.login'))

    return render_template('signup.html', form=form)


@accounts_app.route('/login/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('accounts_app.get_user_profile', user_id=current_user.id))

    form = LoginForm()

    if request.method == 'POST':
        username = form.username.data
        password = form.password.data

        user = User.query.filter_by(username=username).one_or_none()

        if not user:
            flash('This username does not exist, please try again.', category='danger')
            return redirect(url_for('accounts_app.login'))
        elif not check_password_hash(user.password, password):
            flash('Password is incorrect, please try again.', category='danger')
            return redirect(url_for('accounts_app.login'))
        else:
            if request.form.get('checkbox'):
                login_user(user, remember=True)
            else:
                login_user(user)
            flash('You successfully logged in!', category='info')
            return redirect(url_for('main_app.home'))

    return render_template('login.html', form=form)


@accounts_app.route('/logout/')
def logout():
    logout_user()
    return redirect(url_for('accounts_app.login'))


@accounts_app.route('/user/<int:user_id>/')
@login_required
def get_user_profile(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    user_blogs = Blog.query.filter_by(user_id=user_id).order_by(Blog.id.desc()).paginate(per_page=10)
    return render_template('user_profile.html', user=user, user_blogs=user_blogs)


@accounts_app.route('/user/<int:user_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit_user_profile(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = EditUserForm()

    if current_user.id == user_id:
        if request.method == 'POST':
            username = form.username.data
            first_name = form.first_name.data
            last_name = form.last_name.data
            bio = form.bio.data
            email = form.email.data
            password = form.password.data

            hash_and_salted_password = generate_password_hash(
                password,
                method='pbkdf2:sha256',
                salt_length=8,
            )
            user.username = username,
            user.first_name = first_name,
            user.last_name = last_name,
            user.bio = bio,
            user.email = email,
            user.password = hash_and_salted_password
            db.session.commit()

            flash('Your profile has been updated!', category='info')
            return redirect(url_for('accounts_app.get_user_profile', user_id=user_id))

        return render_template('edit_user_profile.html', user=user, form=form)

    else:
        abort(404)

lesson_4/blog_project/views/blogs.py
from functools import wraps

from flask import Blueprint, request, render_template, abort, url_for, redirect, flash
from flask_login import login_required, current_user

from lesson_4.blog_project.models import Blog, User, Comment, db, Tag
from lesson_4.blog_project.forms import CommentForm, BlogForm, TagForm

blogs_app = Blueprint('blogs_app', __name__)


def admin_only(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.is_admin:
            flash('Only admins can access this page.', category='danger')
            return redirect(url_for('main_app.home'))
        return f(*args, **kwargs)

    return decorated_function


@blogs_app.route('/search/', methods=['GET'])
@login_required
def search_blogs():
    keyword = request.args.get('keyword')
    select = request.args.get('select')
    data = None

    if keyword:
        if select == 'blogs':
            data = Blog.query \
                .filter(Blog.text.like('%' + keyword + '%')).order_by(Blog.title) \
                .paginate(per_page=10)
        else:
            data = User.query \
                .filter(User.username.like('%' + keyword + '%')).order_by(User.username) \
                .paginate(per_page=10)

    return render_template('search.html', keyword=keyword, data=data, select=select)


@blogs_app.route('/blog/<int:blog_id>/', methods=['GET', 'POST'])
@login_required
def get_blog(blog_id):
    form = CommentForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            comment_text = form.text.data
            new_comment = Comment(
                text=comment_text,
                user_id=current_user.id,
                blog_id=blog_id
            )
            db.session.add(new_comment)
            db.session.commit()
            return redirect(url_for('blogs_app.get_blog', blog_id=blog_id))
    blog = Blog.query.filter_by(id=blog_id).one_or_none()
    comments = Comment.query.filter_by(blog_id=blog_id).order_by(Comment.id.desc())

    return render_template('get_blog.html', blog=blog, form=form, comments=comments)


@blogs_app.route('/add-blog/', methods=['GET', 'POST'])
@login_required
def add_blog():
    tags = Tag.query.all()
    form = BlogForm()

    if request.method == 'POST':
        tag_ids = form.tags.data
        tags = [Tag.query.filter_by(id=tag_id).one_or_none() for tag_id in tag_ids]
        new_blog = Blog(
            title=form.title.data,
            text=form.text.data,
            tags=tags,
            user=current_user,
        )
        db.session.add(new_blog)
        db.session.commit()

        flash('The blog has been created.', category='info')
        referrer = request.form.get('referrer')
        if 'user' in referrer:
            return redirect(url_for('accounts_app.get_user_profile', user_id=current_user.id))
        return redirect(url_for('main_app.home'))

    return render_template('add_blog.html', tags=tags, form=form)


@blogs_app.route('/edit-blog/<int:blog_id>/', methods=['GET', 'POST'])
@login_required
def edit_blog(blog_id):
    blog = Blog.query.filter_by(id=blog_id).first_or_404()
    tags = Tag.query.all()
    form = BlogForm()
    if current_user.id == blog.user_id:
        if request.method == 'GET':
            form.text.data = blog.text
        if request.method == 'POST':
            tag_ids = form.tags.data
            tags = [Tag.query.filter_by(id=tag_id).one_or_none() for tag_id in tag_ids]
            blog.title = form.title.data
            blog.text = form.text.data
            blog.tags = tags

            db.session.commit()
            flash('The blog has been edited.', category='info')
            return redirect(url_for('blogs_app.get_blog', blog_id=blog_id))

        return render_template('edit_blog.html', blog=blog, tags=tags, form=form)

    else:
        abort(404)


@blogs_app.route('/all-tags/')
@login_required
@admin_only
def all_tags():
    tags = Tag.query.all()
    return render_template('all_tags.html', tags=tags)


@blogs_app.route('/add-tag/', methods=['GET', 'POST'])
@login_required
@admin_only
def add_tag():
    form = TagForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            new_tag = Tag(
                name=form.name.data,
                color=form.color.data[1:],
            )
            db.session.add(new_tag)
            db.session.commit()
            flash('The tag has been successfully created.', category='info')
            return redirect(url_for('blogs_app.all_tags'))

    return render_template('add_tag.html', form=form)


@blogs_app.route('/edit-tag/<int:tag_id>/', methods=['GET', 'POST'])
@login_required
@admin_only
def edit_tag(tag_id):
    tag = Tag.query.filter_by(id=tag_id).one()
    tag_color = f'#{tag.color}'
    form = TagForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            tag.name = form.name.data
            tag.color = form.color.data[1:]
            db.session.commit()
            flash('The tag has been successfully updated.', category='info')
            return redirect(url_for('blogs_app.all_tags'))

    return render_template('edit_tag.html', tag=tag, form=form, tag_color=tag_color)


@blogs_app.route('/delete-tag/<int:tag_id>/', methods=['GET', 'POST'])
@login_required
@admin_only
def delete_tag(tag_id):
    tag = Tag.query.filter_by(id=tag_id).one()
    if request.method == 'POST':
        db.session.delete(tag)
        db.session.commit()
        return redirect(url_for('blogs_app.all_tags'))

    return render_template('delete_tag.html', tag=tag)

lesson_4/blog_project/views/main.py
from flask import Blueprint, render_template
from flask_login import login_required

from lesson_4.blog_project.models import Blog

main_app = Blueprint('main_app', __name__)


@main_app.route('/')
@login_required
def home():
    all_blogs = Blog.query.order_by(Blog.id.desc()).paginate(per_page=10)
    return render_template('home.html', all_blogs=all_blogs)


@main_app.route('/about/')
@login_required
def about():
    return render_template('about.html')

lesson_4/blog_project/templates/add_blog.html
{% extends 'base.html' %}

{% block title %}Add a new blog{% endblock %}

{% block content %}

    <div class="container content">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                {% if 'user' in request.referrer %}
                    <a href="{{ url_for('accounts_app.get_user_profile', user_id=user.id) }}" class="btn btn-danger mt-4 mb-3">
                        <i class="fa-solid fa-angle-left"></i>
                        Go back
                    </a>
                {% else %}
                    <a href="{{ url_for('main_app.home') }}" class="btn btn-danger mt-4 mb-3">
                        <i class="fa-solid fa-angle-left"></i>
                        Go back
                    </a>
                {% endif %}
                <h1 class="text-center text-white">Add a new blog</h1>
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <form method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.title.label(class='form-label text-white') }}
                        {{ form.title(id='title', class='form-control') }}
                    </div>
                    <label for="text" class="form-label text-white">Text</label>
                    <div class="mb-3">
                        {{ form.text() }}
                    </div>
                    <label for="tags" class="text-white">Choose a tag</label>
                    <div class="mb-3">
                        <select id="tags" name="tags" multiple>
                            {% for tag in tags %}
                                <option value="{{ tag.id }}">{{ tag.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <input type="hidden" name="referrer" value="{{ request.referrer }}">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="col-3"></div>
        </div>
    </div>

{% endblock %}

lesson_4/blog_project/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet">

    <!-- Icons -->
    <script src="https://kit.fontawesome.com/148fa55e15.js" crossorigin="anonymous"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <title>
        {% block title %}
        {% endblock %}
    </title>

    {{ ckeditor.load() }}
</head>

<body>

<canvas id="canvas"></canvas>

<div class="objects">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main_app.home') }}">My Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                    aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active px-3" aria-current="page" href="{{ url_for('main_app.home') }}">
                            <i class="fa-solid fa-house"></i>  Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-3" aria-current="page" href="{{ url_for('main_app.about') }}">
                            <i class="fa-solid fa-info"></i>  About
                        </a>
                    </li>
                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link px-3" aria-current="page" href="{{ url_for('accounts_app.login') }}">
                                <i class="fa-solid fa-key"></i>  Login
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-3" aria-current="page" href="{{ url_for('accounts_app.signup') }}">
                                <i class="fa-solid fa-user-plus"></i>  Sign Up
                            </a>
                        </li>
                        <li class="nav-item">
                            <p class="online-text p-2 m-0"><span class="offline-dot"><b> • </b></span>You're logged out
                            </p>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link px-3" aria-current="page"
                               href="{{ url_for('accounts_app.get_user_profile', user_id=current_user.id) }}">
                                <i class="fa-solid fa-user"></i>  Profile
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-3" aria-current="page" href="{{ url_for('accounts_app.logout') }}">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>  Log Out
                            </a>
                        </li>
                        <li class="nav-item">
                            <p class="online-text p-2 m-0"><span class="online-dot"><b> • </b></span>{{ user.username }}
                            </p>
                        </li>
                    {% endif %}
                </ul>
                <form method="get" action="{{ url_for('blogs_app.search_blogs') }}" class="d-flex">
                    <select class="form-select form-select-sm me-2" aria-label=".form-select-sm example" name="select">
                        <option value="users" selected>Users</option>
                        <option value="blogs">Blogs</option>
                    </select>
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                           name="keyword">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

</div>

<footer class="bg-dark text-center text-lg-start mt-5">
    <div class="container p-4">
        <div class="text-center">
            <h5 class="text-uppercase">My Blog Project</h5>
            <p>
                Share everything!
            </p>
        </div>
    </div>
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © <span id="copyright-year">YYYY</span> Copyright
    </div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<!-- Custom JavaScript -->
<script src="{{ url_for('static', filename='js/animation.js') }}"></script>
<script src="{{ url_for('static', filename='js/copyright_year.js') }}"></script>
<script src="{{ url_for('static', filename='js/eye.js') }}"></script>

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>

</html>

lesson_4/blog_project/templates/user_profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}

    <div class="container content">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="mt-4">
                    {% include 'includes/messages.html' %}
                </div>
                <div class="row">
                    <div class="col-2"></div>
                    <div class="col-8">
                        <div class="text-center mb-4 mt-4 p-3">
                            <h1 class="pb-2 text-white">@{{ user.username }}
                                {% if current_user.id == user.id %}
                                     <a href="{{ url_for('accounts_app.edit_user_profile', user_id=user.id) }}"
                                        class="btn btn-primary btn-sm">
                                        <i class="fa-solid fa-pen-to-square"></i>  Edit profile
                                    </a>
                                {% endif %}
                            </h1>
                            {% if user.is_admin %}
                                <h5><span class="badge bg-secondary mb-3">Admin</span></h5>
                            {% endif %}
                            {% if user.first_name and user.last_name %}
                                <h4 class="text-white">{{ user.first_name }} {{ user.last_name }}</h4>
                            {% elif user.first_name %}
                                <h4 class="text-white">{{ user.first_name }}</h4>
                            {% elif user.last_name %}
                                <h4 class="text-white">{{ user.last_name }}</h4>
                            {% endif %}
                            {% if user.bio %}
                                {{ user.bio|safe }}
                            {% else %}
                                <p class="fst-italic text-white mb-0">No bio is provided</p>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-2"></div>
                </div>
                <div class="text-center pb-3">
                    {% if current_user.id == user.id %}
                        <a href="{{ url_for('blogs_app.add_blog') }}" class="btn btn-success m-2">
                            <i class="fa-solid fa-plus"></i>  Add a new blog
                        </a>
                    {% endif %}
                </div>
                {% if user_blogs.items %}
                    {% for blog in user_blogs.items %}
                        <div class="py-2">
                            <div class="card">
                                <div class="card-header">
                                    <div class="row">
                                        <div class="col-6">
                                            <p class="mb-0 h5">@{{ blog.user.username }}</p>
                                        </div>
                                        <div class="col-6">
                                            <p class="date mb-0">
                                                <i class="fa-solid fa-calendar-days"></i>
                                                {{ blog.created_at.strftime('%H:%S') }} •
                                                {{ blog.created_at.strftime('%d %b %Y') }}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    {% if blog.tags %}
                                        {% for tag in blog.tags %}
                                            <span class="badge"
                                                  style="background-color: #{{ tag.color }};">{{ tag }}</span>
                                        {% endfor %}
                                    {% endif %}
                                    <h3 class="card-title pt-2">{{ blog.title }}</h3>
                                    <p class="card-text">
                                        {{ blog.text|safe }}
                                    </p>
                                    <a href="{{ url_for('blogs_app.get_blog', blog_id=blog.id) }}"
                                       class="btn btn-success">Details</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    {% if user_blogs.pages > 1 %}
                        <nav>
                            <ul class="pagination justify-content-center mt-4">
                                {% if user_blogs.has_prev %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="{{ url_for('accounts_app.get_user_profile', user_id=user.id, page=user_blogs.prev_num) }}">
                                            Previous
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="page-item"><a class="page-link btn disabled" href="#">Previous</a></li>
                                {% endif %}
                                {% for page_num in user_blogs.iter_pages() %}
                                    <li class="page-item {% if page_num == user_blogs.page %}active{% endif %}">
                                        <a class="page-link"
                                           href="{{ url_for('accounts_app.get_user_profile', user_id=user.id, page=page_num) }}">
                                            {{ page_num }}
                                        </a>
                                    </li>
                                {% endfor %}
                                {% if user_blogs.has_next %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="{{ url_for('accounts_app.get_user_profile', user_id=user.id, page=user_blogs.next_num) }}">
                                            Next
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="page-item"><a class="page-link btn disabled" href="#">Next</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}
                {% else %}
                    <p class="text-center text-white fst-italic">The user has not posted anything yet.</p>
                {% endif %}
            </div>
            <div class="col-2"></div>
        </div>
    </div>

{% endblock %}