lesson_7/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.authtoken.views import obtain_auth_token
from graphene_django.views import GraphQLView

from config.settings import DEBUG
from config.api.views import APIRootView
from onlineschool.views import HomeTemplateView, Contact, APITemplateView, generate_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', HomeTemplateView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('courses/', include('onlineschool.urls')),
    path('contact/', Contact.as_view(), name='contact'),
    path('api-token/', APITemplateView.as_view(), name='api_token'),
    path('generate-token/', generate_token, name='generate_token'),

    # Rest Framework
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token),
    path('api/v1/', APIRootView.as_view(), name='api_root_view'),
    path('api/v1/', include('onlineschool.api.urls')),
    path('api/v1/', include('accounts.api.urls')),

    # GraphQL
    path('graphql/', GraphQLView.as_view()),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]
    urlpatterns.insert(0, path('graphql/', GraphQLView.as_view(graphiql=True)))

lesson_7/onlineschool/api/urls.py
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()

router.register(r'course', views.CourseViewSet)
router.register(r'schedule', views.ScheduleViewSet)
router.register(r'category', views.CategoryViewSet)
router.register(r'teacher', views.TeacherViewSet)
router.register(r'student', views.StudentViewSet)
router.register(r'registration-request', views.RegistrationRequestViewSet)
router.register(r'course-request', views.CourseRequestViewSet)
router.register(r'student-courses', views.StudentCoursesViewSet, basename='student_courses')

app_name = 'onlineschool_api'

urlpatterns = router.urls

lesson_7/onlineschool/urls.py
from django.urls import path

from . import views

app_name = 'onlineschool'

urlpatterns = [
    path('', views.CourseListView.as_view(), name='courses'),
    path('search/', views.SearchCourseListView.as_view(), name='search'),
    path('schedule/', views.ScheduleListView.as_view(), name='schedule'),
    path('schedule-calendar/', views.ScheduleCalendarView.as_view(), name='schedule_calendar'),
    path('schedule-calendar-nav/', views.get_month_ajax, name='schedule_calendar_nav'),
    path('create-course/', views.CourseCreateView.as_view(), name='create_course'),
    path('update-course/<slug:course_slug>/', views.CourseUpdateView.as_view(), name='update_course'),
    path('delete-course/<slug:course_slug>/', views.CourseDeleteView.as_view(), name='delete_course'),
    path('create-category/', views.CategoryCreateView.as_view(), name='create_category'),
    path('update-category/<slug:category_slug>/', views.CategoryUpdateView.as_view(), name='update_category'),
    path('delete-category/<slug:category_slug>/', views.CategoryDeleteView.as_view(), name='delete_category'),
    path('create-group/', views.GroupCreateView.as_view(), name='create_group'),
    path('update-group/<slug:group_slug>/', views.GroupUpdateView.as_view(), name='update_group'),
    path('delete-group/<slug:group_slug>/', views.GroupDeleteView.as_view(), name='delete_group'),
    path('my-courses/', views.StudentCoursesListView.as_view(), name='student_courses'),
    path('category/<slug:category_slug>/', views.CourseByCategoryListView.as_view(), name='course_by_category'),
    path('registration-requests/', views.RegistrationRequestListView.as_view(), name='registration_requests'),
    path('delete-request/<int:pk>/', views.RegistrationRequestDeleteView.as_view(), name='delete_request'),
    path('add-to-group/<slug:course_slug>/<int:user_id>/', views.add_student_to_group, name='add_student_to_group'),
    path('<slug:course_slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('<slug:course_slug>/register/', views.register_registration_request, name='register_registration_request'),
    path('<slug:course_slug>/course-request/', views.register_course_request, name='register_course_request'),
    path(
        'send-registration-link/<str:email>/<slug:course_slug>/',
        views.send_registration_link, name='send_registration_link',
    ),
]

lesson_7/onlineschool/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group, Permission
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

from slugify import slugify

User = get_user_model()


class Teacher(models.Model):
    user = models.OneToOneField(User, verbose_name='Пользователь', on_delete=models.CASCADE, unique=True)
    short_bio = models.CharField('Короткая биография/специальность', max_length=64)
    bio = RichTextUploadingField('Биография')

    class Meta:
        verbose_name = 'преподаватель'
        verbose_name_plural = 'Преподаватели'

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        student_exists = Student.objects.filter(user=self.user)
        if student_exists:
            raise ValidationError('Уже существует студент с этим профилем')
        super().save(*args, **kwargs)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь', unique=True)
    wishlist = models.ManyToManyField(
        'Course', verbose_name='Список желаемого', related_name='student_wishlist', blank=True
    )

    class Meta:
        verbose_name = 'студент'
        verbose_name_plural = 'Студенты'

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        teacher_exists = Teacher.objects.filter(user=self.user)
        if teacher_exists:
            raise ValidationError('Уже существует преподаватель с этим профилем')
        super().save(*args, **kwargs)


# Auto create Teacher or Student (one to one) when User is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == '1':
            group = Group.objects.filter(name='Учитель').first()
            if not group:
                group = Group.objects.create(name='Учитель')
                all_models = ['course', 'schedule', 'category', 'registrationrequest', 'courserequest']
                prefixes = ['add', 'change', 'delete', 'view']
                for model in all_models:
                    for prefix in prefixes:
                        try:
                            permission = Permission.objects.get(codename=f'{prefix}_{model}')
                        except Permission.DoesNotExist:
                            print(f'Permission with name "can_{prefix}_{model}" does not exist.')
                            continue
                        group.permissions.add(permission)
            instance.groups.add(group)
            Teacher.objects.create(user=instance)
        else:
            Student.objects.create(user=instance)


class Review(models.Model):
    student = models.ForeignKey(Student, verbose_name='Студент', on_delete=models.CASCADE)
    rating = models.PositiveIntegerField('Оценка', validators=[MinValueValidator(0), MaxValueValidator(5)])
    text = RichTextUploadingField('Описание')

    class Meta:
        verbose_name = 'отзыв'
        verbose_name_plural = 'Отзывы'

    def __str__(self):
        return str(self.student)


class Category(models.Model):
    name = models.CharField('Название', max_length=100)
    color = models.CharField('Цвет', max_length=7, default='#0D6EFD')
    slug = models.SlugField('URL', max_length=150, unique=True)

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            new_slug = slugify(self.name)
            slug_exists = Category.objects.filter(slug=new_slug).exists()
            if slug_exists:
                self.slug = f'{str(new_slug)}-{str(self.id)}'
            else:
                self.slug = new_slug
            self.save()


class Course(models.Model):
    category = models.ForeignKey('Category', verbose_name='Категория', on_delete=models.CASCADE)
    name = models.CharField('Название', max_length=200)
    photo = models.ImageField('Фотография', blank=True, null=True, default='course_default.png')
    duration = models.PositiveIntegerField('Длительность (в мес.)')
    short_description = RichTextUploadingField('Краткое описание', blank=True, null=True)
    description = RichTextUploadingField('Описание')
    teachers = models.ManyToManyField('Teacher', verbose_name='Преподаватели')
    required_knowledge = RichTextUploadingField('Необходимые знания')
    after_course = RichTextUploadingField('После обучения')
    price = models.PositiveIntegerField('Стоимость (в руб.)', blank=True, null=True)
    slug = models.SlugField('URL', max_length=250, unique=True)

    class Meta:
        verbose_name = 'курс'
        verbose_name_plural = 'Курсы'
        ordering = ('-id',)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            new_slug = slugify(self.name)
            slug_exists = Course.objects.filter(slug=new_slug).exists()
            if slug_exists:
                self.slug = f'{str(new_slug)}-{str(self.id)}'
            else:
                self.slug = new_slug
            self.save()


class Schedule(models.Model):
    course = models.ForeignKey(Course, verbose_name='Курс', on_delete=models.CASCADE)
    students = models.ManyToManyField(Student, verbose_name='Студенты', blank=True)
    start_date = models.DateField('Дата старта курса')
    end_date = models.DateField('Дата окончания курса')
    is_announced_later = models.BooleanField('Не показывать дату начала курса?')
    slug = models.SlugField('URL', max_length=250, unique=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            new_slug = slugify(f'{self.course.name}-{self.start_date.month}-{self.start_date.year}')
            slug_exists = Schedule.objects.filter(slug=new_slug).exists()
            if slug_exists:
                self.slug = f'{str(new_slug)}-{str(self.id)}'
            else:
                self.slug = new_slug
            self.save()

    @property
    def get_html_course_url(self):
        url = reverse('onlineschool:course_detail', args=[self.course.slug])
        return f'<a href="{url}"> {self.course.name} </a>'

    class Meta:
        verbose_name = 'расписание'
        verbose_name_plural = 'Расписание'
        ordering = ('is_announced_later', 'start_date')

    def __str__(self):
        return f'{self.course} - {self.start_date}'


class RegistrationBase(models.Model):
    student = models.ForeignKey(Student, verbose_name='Студент', on_delete=models.CASCADE, blank=True, null=True)
    email = models.EmailField('Почта', max_length=32)
    course = models.ForeignKey(Course, verbose_name='Курс', on_delete=models.CASCADE)
    date_created = models.DateField('Дата создания', auto_now_add=True)

    class Meta:
        abstract = True

    def __str__(self):
        return str(self.email)


class RegistrationRequest(RegistrationBase):
    class Meta:
        ordering = ['-date_created']
        verbose_name = 'заявка на запись'
        verbose_name_plural = 'Заявки на запись'


class CourseRequest(RegistrationBase):
    class Meta:
        verbose_name = 'заявка о старте набора'
        verbose_name_plural = 'Заявки о старте набора'

lesson_7/onlineschool/api/views.py
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet

from ..models import Course, Schedule, Category, Teacher, Student, RegistrationRequest, CourseRequest
from .serializers import (
    CourseSerializer,
    ScheduleSerializer,
    CategorySerializer,
    TeacherSerializer,
    StudentSerializer,
    RegistrationRequestSerializer,
    CourseRequestSerializer, StudentCoursesSerializer
)
from .permissions import IsTeacherPermission, IsStudentPermission


class CourseViewSet(ModelViewSet):
    queryset = Course.objects
    serializer_class = CourseSerializer

    def get_queryset(self):
        return super().get_queryset() \
            .select_related('category') \
            .prefetch_related('teachers', 'teachers__user')


class ScheduleViewSet(ModelViewSet):
    queryset = Schedule.objects
    serializer_class = ScheduleSerializer

    def get_queryset(self):
        return super().get_queryset() \
            .select_related('course') \
            .prefetch_related('students', 'students__user')


class CategoryViewSet(ModelViewSet):
    queryset = Category.objects
    serializer_class = CategorySerializer


class TeacherViewSet(ModelViewSet):
    queryset = Teacher.objects
    serializer_class = TeacherSerializer

    def get_queryset(self):
        return super().get_queryset().select_related('user')


class StudentViewSet(ModelViewSet):
    queryset = Student.objects
    serializer_class = StudentSerializer

    def get_queryset(self):
        return super().get_queryset().select_related('user').prefetch_related('wishlist')


class RegistrationRequestViewSet(ModelViewSet):
    permission_classes = [IsTeacherPermission]
    queryset = RegistrationRequest.objects
    serializer_class = RegistrationRequestSerializer

    def get_queryset(self):
        return super().get_queryset().select_related('student', 'student__user', 'course')


class CourseRequestViewSet(ModelViewSet):
    permission_classes = [IsTeacherPermission]
    queryset = CourseRequest.objects
    serializer_class = CourseRequestSerializer

    def get_queryset(self):
        return super().get_queryset().select_related('student', 'student__user', 'course')


class StudentCoursesViewSet(ReadOnlyModelViewSet):
    permission_classes = [IsStudentPermission]
    queryset = Schedule.objects
    serializer_class = StudentCoursesSerializer

    def get_queryset(self):
        return super().get_queryset().filter(students__user=self.request.user)

lesson_7/onlineschool/views/calendar.py
import calendar
from datetime import datetime, timedelta

from django.http import JsonResponse
from django.views.generic import ListView
from django.utils.safestring import mark_safe

from ..models import Schedule
from ..forms import DateForm
from ..utils import EventCalendar


def get_date(req_day):
    if req_day:
        try:
            year, month, day = (int(x) for x in req_day.split('-'))
            return datetime(year, month, day)
        except ValueError:
            year, month = (int(x) for x in req_day.split('-'))
            return datetime(year, month, day=1)
    return datetime.today()


def get_prev_month(current_date):
    first = current_date.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'date=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def get_next_month(current_date):
    days_in_month = calendar.monthrange(current_date.year, current_date.month)[1]
    last = current_date.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'date=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def get_current_month(current_date):
    month = 'date=' + str(current_date.year) + '-' + str(current_date.month)
    return month


def get_month_ajax(request):
    date = get_date(request.GET.get('date', None))
    cal = EventCalendar(date.year, date.month, date.day)
    html_cal = cal.formatmonth(withyear=True)
    prev_month = get_prev_month(date)
    next_month = get_next_month(date)
    return JsonResponse({'data': html_cal, 'prev_month': prev_month, 'next_month': next_month})


class ScheduleCalendarView(ListView):
    model = Schedule
    template_name = 'onlineschool/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_date = get_date(self.request.GET.get('date', None))
        cal = EventCalendar(current_date.year, current_date.month, current_date.day)
        html_cal = cal.formatmonth(withyear=True)

        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = get_prev_month(current_date)
        context['next_month'] = get_next_month(current_date)
        context['current_month'] = get_current_month(current_date)
        context['form'] = DateForm()

        return context

lesson_7/onlineschool/templates/onlineschool/course_detail.html
{% extends 'base.html' %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row pb-5">
            {% include 'includes/messages.html' %}
            <div class="col-7">
                <div class="my-5">
                    <h1>{{ object.name }}
                        {% if request.user.user_type == '1' %}
                            <a href="{% url 'onlineschool:update_course' course_slug=object.slug %}"
                               class="btn btn-success">
                                <i class="fa-solid fa-pen-to-square"></i>  Редактировать
                            </a>
                            <a href="{% url 'onlineschool:delete_course' course_slug=object.slug %}"
                               class="btn btn-danger">
                                <i class="fa-solid fa-trash-can"></i>  Удалить
                            </a>
                        {% endif %}
                    </h1>

                    {% if object.short_description %}
                        <p>{{ object.short_description|safe }}</p>
                    {% endif %}

                    <h5>Ближайшая группа:</h5>

                    {% if not group.is_announced_later %}
                        {% if group %}
                            <p class="card-text">
                                <i class="fa-solid fa-calendar-days"></i> с {{ group.start_date }}
                            </p>
                            {% if user_in_group %}
                                <a href="#" class="btn btn-success disabled">Вас записали в группу</a>
                            {% else %}
                                {% if request.user.is_authenticated %}
                                    {% if registration_request_exists %}
                                        <a href="#" class="btn btn-primary disabled">Заявка на запись подана</a>
                                    {% else %}
                                        <a href="{% url 'onlineschool:register_registration_request' course_slug=object.slug %}"
                                            class="btn btn-primary">Записаться</a>
                                    {% endif %}
                                {% else %}
                                    <form method="post" class="row g-2"
                                        action="{% url 'onlineschool:register_registration_request' course_slug=object.slug %}">
                                        {% csrf_token %}
                                        <div class="col-auto">
                                            <input type="email" name="email" class="form-control" placeholder="Ваша почта">
                                        </div>
                                        <div class="col-auto">
                                            <input type="submit" class="btn btn-primary" value="Записаться">
                                        </div>
                                    </form>
                                {% endif %}
                            {% endif %}
                        {% else %}
                            <p class="card-text">
                                <i class="fa-solid fa-calendar-days"></i> о дате старта будет объявлено позже
                            </p>
                            {% if request.user.is_authenticated %}
                                {% if course_request_exists %}
                                    <a href="#" class="btn btn-primary disabled">Мы вам сообщим о старте курса</a>
                                {% else %}
                                    <a href="{% url 'onlineschool:register_course_request' course_slug=object.slug %}"
                                       class="btn btn-primary">Сообщить о старте набора</a>
                                {% endif %}
                            {% else %}
                                <form method="post" class="row g-2"
                                    action="{% url 'onlineschool:register_course_request' course_slug=object.slug %}">
                                    {% csrf_token %}
                                    <div class="col-auto">
                                        <input type="email" name="email" class="form-control" placeholder="Ваша почта">
                                    </div>
                                    <div class="col-auto">
                                        <input type="submit" class="btn btn-primary" value="Сообщить о старте набора">
                                    </div>
                                </form>
                            {% endif %}
                        {% endif %}
                    {% else %}
                        <p class="card-text">
                            <i class="fa-solid fa-calendar-days"></i> о дате старта будет объявлено позже
                        </p>
                        {% if request.user.is_authenticated %}
                            {% if course_request_exists %}
                                <a href="#" class="btn btn-primary disabled">Мы вам сообщим о старте курса</a>
                            {% else %}
                                <a href="{% url 'onlineschool:register_course_request' course_slug=object.slug %}"
                                   class="btn btn-primary">Сообщить о старте набора</a>
                            {% endif %}
                        {% else %}
                            <form method="post" class="row g-2"
                                action="{% url 'onlineschool:register_course_request' course_slug=object.slug %}">
                                {% csrf_token %}
                                <div class="col-auto">
                                    <input type="email" name="email" class="form-control" placeholder="Ваша почта">
                                </div>
                                <div class="col-auto">
                                    <input type="submit" class="btn btn-primary" value="Сообщить о старте набора">
                                </div>
                            </form>
                        {% endif %}
                    {% endif %}

                </div>
            </div>
            <div class="col-5">
                <img src="{{ object.photo.url }}" alt="..." width="70%" height="auto" class="mx-auto d-block">
            </div>
        </div>
    </div>
    <div class="py-5" style="background-color: #F8F9FA">
        <div class="container">
            <h3 class="text-center">Описание курса:</h3>
            <p>{{ object.description|safe }}</p>
        </div>
    </div>
    <div class="container py-5">
        <h3 class="text-center">Преподаватели:</h3>
        {% for teacher in object.teachers.all %}
            <div class="row py-2">
                <div class="col-3">
                    <img src="{{ teacher.user.photo.url }}" alt="" width="70%" height="auto">
                </div>
                <div class="col-7">
                    <h5>{{ teacher.user.get_full_name }}</h5>
                    <p>{{ teacher.bio|safe }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="py-5" style="background-color: #F8F9FA">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <h3 class="text-center">Необходимые знания:</h3>
                    <p>{{ object.required_knowledge|safe }}</p>
                </div>
                <div class="col-6">
                    <h3 class="text-center">После обучения:</h3>
                    <p>{{ object.after_course|safe }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="py-5" style="background-color: #7effc5">
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <p>Стоимость обучения</p>
                    <h4>{{ course.price }}₽</h4>
                </div>
                <div class="col-4">
                    <p>Продолжительность</p>
                    <h4>{{ course.duration }} месяцев</h4>
                    {% for group in object.schedule_set.all %}
                        {% if forloop.first %}
                            <p>Начало занятий</p>
                            <h4>{{ group.start_date }}</h4>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="col-4">
                    <h5>Ближайшая группа:</h5>
                    {% if not group.is_announced_later %}
                        {% if group %}
                            <p class="card-text">
                                <i class="fa-solid fa-calendar-days"></i> с {{ group.start_date }}
                            </p>
                            {% if user_in_group %}
                                <a href="#" class="btn btn-success disabled">Вас записали в группу</a>
                            {% else %}
                                {% if request.user.is_authenticated %}
                                    {% if registration_request_exists %}
                                        <a href="#" class="btn btn-primary disabled">Заявка на запись подана</a>
                                    {% else %}
                                        <a href="{% url 'onlineschool:register_registration_request' course_slug=object.slug %}"
                                            class="btn btn-primary">Записаться</a>
                                    {% endif %}
                                {% else %}
                                    <form method="post" class="row g-2"
                                        action="{% url 'onlineschool:register_registration_request' course_slug=object.slug %}">
                                        {% csrf_token %}
                                        <div class="col-auto">
                                            <input type="email" name="email" class="form-control" placeholder="Ваша почта">
                                        </div>
                                        <div class="col-auto">
                                            <input type="submit" class="btn btn-primary" value="Записаться">
                                        </div>
                                    </form>
                                {% endif %}
                            {% endif %}
                        {% else %}
                            <p class="card-text">
                                <i class="fa-solid fa-calendar-days"></i> о дате старта будет объявлено позже
                            </p>
                            {% if request.user.is_authenticated %}
                                {% if course_request_exists %}
                                    <a href="#" class="btn btn-primary disabled">Мы вам сообщим о старте курса</a>
                                {% else %}
                                    <a href="{% url 'onlineschool:register_course_request' course_slug=object.slug %}"
                                       class="btn btn-primary">Сообщить о старте набора</a>
                                {% endif %}
                            {% else %}
                                <form method="post" class="row g-2"
                                    action="{% url 'onlineschool:register_course_request' course_slug=object.slug %}">
                                    {% csrf_token %}
                                    <div class="col-auto">
                                        <input type="email" name="email" class="form-control" placeholder="Ваша почта">
                                    </div>
                                    <div class="col-auto">
                                        <input type="submit" class="btn btn-primary" value="Сообщить о старте набора">
                                    </div>
                                </form>
                            {% endif %}
                        {% endif %}
                    {% else %}
                        <p class="card-text">
                            <i class="fa-solid fa-calendar-days"></i> о дате старта будет объявлено позже
                        </p>
                        {% if request.user.is_authenticated %}
                            {% if course_request_exists %}
                                <a href="#" class="btn btn-primary disabled">Мы вам сообщим о старте курса</a>
                            {% else %}
                                <a href="{% url 'onlineschool:register_course_request' course_slug=object.slug %}"
                                   class="btn btn-primary">Сообщить о старте набора</a>
                            {% endif %}
                        {% else %}
                            <form method="post" class="row g-2"
                                action="{% url 'onlineschool:register_course_request' course_slug=object.slug %}">
                                {% csrf_token %}
                                <div class="col-auto">
                                    <input type="email" name="email" class="form-control" placeholder="Ваша почта">
                                </div>
                                <div class="col-auto">
                                    <input type="submit" class="btn btn-primary" value="Сообщить о старте набора">
                                </div>
                            </form>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

lesson_7/onlineschool/templates/onlineschool/registrationrequest_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Удалить заявку {{ object }}{% endblock %}

{% block content %}

    <div class="container my-5">
        <h1 class="text-center">Удалить заявку {{ object }}</h1>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <form method="post">
                    {% csrf_token %}
                    <p>Вы уверены, что хотите удалить заявку "{{ object }} от {{ object.date_created }}"?</p>
                    {{ form }}
                    <button type="submit" class="btn btn-danger"><i class="fa-solid fa-trash-can"></i>  Да, удалить
                    </button>
                </form>
                <a href="{% url 'onlineschool:registration_requests' %}" class="btn btn-primary mt-1">
                    <i class="fa-solid fa-arrow-left"></i>  Назад
                </a>
            </div>
            <div class="col-4"></div>
        </div>
    </div>

{% endblock %}