lesson_5/blog_project/forms/blogs.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectMultipleField
from wtforms.validators import DataRequired
from flask_ckeditor import CKEditorField


class CommentForm(FlaskForm):
    text = StringField('Text', validators=[DataRequired()])


class BlogForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = CKEditorField('Text', validators=[DataRequired()])
    tags = SelectMultipleField('Choose a tag', coerce=int)


class TagForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    color = StringField('Select color:', validators=[DataRequired()])

lesson_5/blog_project/views/blogs.py
from functools import wraps

from flask import Blueprint, request, render_template, abort, url_for, redirect, flash
from flask_login import login_required, current_user

from ..models import db, Blog, User, Comment, Tag
from ..forms import CommentForm, BlogForm, TagForm

blogs_app = Blueprint('blogs_app', __name__)


def admin_only(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.is_admin:
            flash('Only admins can access this page.', category='danger')
            return redirect(url_for('main_app.home'))
        return f(*args, **kwargs)

    return decorated_function


@blogs_app.route('/search/', methods=['GET'])
@login_required
def search_blogs():
    keyword = request.args.get('keyword')
    select = request.args.get('select')
    data = None

    if keyword:
        if select == 'blogs':
            data = Blog.query \
                .filter(Blog.text.like('%' + keyword + '%')).order_by(Blog.title) \
                .paginate(per_page=10)
        else:
            data = User.query \
                .filter(User.username.like('%' + keyword + '%')).order_by(User.username) \
                .paginate(per_page=10)

    return render_template('blogs/search.html', keyword=keyword, data=data, select=select)


@blogs_app.route('/blog/<int:blog_id>/', methods=['GET', 'POST'])
@login_required
def get_blog(blog_id):
    form = CommentForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            comment_text = form.text.data
            new_comment = Comment(
                text=comment_text,
                user_id=current_user.id,
                blog_id=blog_id
            )
            db.session.add(new_comment)
            db.session.commit()
            return redirect(url_for('blogs_app.get_blog', blog_id=blog_id))

    blog = Blog.query.filter_by(id=blog_id).one_or_none()
    comments = Comment.query.filter_by(blog_id=blog_id).order_by(Comment.id.desc())

    return render_template('blogs/get_blog.html', blog=blog, form=form, comments=comments)


@blogs_app.route('/add-blog/', methods=['GET', 'POST'])
@login_required
def add_blog():
    tags = Tag.query.all()
    form = BlogForm()
    form.tags.choices = [(tag.id, tag.name) for tag in tags]

    if request.method == 'POST':
        if form.validate_on_submit():
            tag_ids = form.tags.data
            tags = [Tag.query.filter_by(id=tag_id).one_or_none() for tag_id in tag_ids]
            new_blog = Blog(
                title=form.title.data,
                text=form.text.data,
                tags=tags,
                user=current_user,
            )
            db.session.add(new_blog)
            db.session.commit()

            flash('The blog has been created.', category='info')
            referrer = request.form.get('referrer')
            if 'user' in referrer:
                return redirect(url_for('accounts_app.get_user_profile', user_id=current_user.id))
            return redirect(url_for('main_app.home'))
        else:
            print(f'ERROR: {form.errors}')

    return render_template('blogs/add_blog.html', form=form)


@blogs_app.route('/edit-blog/<int:blog_id>/', methods=['GET', 'POST'])
@login_required
def edit_blog(blog_id):
    blog = Blog.query.filter_by(id=blog_id).first_or_404()
    tags = Tag.query.all()
    form = BlogForm()
    form.tags.choices = [(tag.id, tag.name) for tag in tags]

    if current_user.id == blog.user_id:
        if request.method == 'GET':
            form.text.data = blog.text
            form.tags.data = [tag.id for tag in blog.tags]
        if request.method == 'POST':
            if form.validate_on_submit():
                tag_ids = form.tags.data
                tags = [Tag.query.filter_by(id=tag_id).one_or_none() for tag_id in tag_ids]
                blog.title = form.title.data
                blog.text = form.text.data
                blog.tags = tags
                db.session.commit()

                flash('The blog has been edited.', category='info')
                return redirect(url_for('blogs_app.get_blog', blog_id=blog_id))
            else:
                print(form.errors)

        return render_template('blogs/edit_blog.html', blog=blog, form=form)

    else:
        abort(404)


@blogs_app.route('/all-tags/')
@login_required
@admin_only
def all_tags():
    tags = Tag.query.all()
    return render_template('blogs/all_tags.html', tags=tags)


@blogs_app.route('/add-tag/', methods=['GET', 'POST'])
@login_required
@admin_only
def add_tag():
    form = TagForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            new_tag = Tag(
                name=form.name.data,
                color=form.color.data[1:],
            )
            db.session.add(new_tag)
            db.session.commit()
            flash('The tag has been successfully created.', category='info')
            return redirect(url_for('blogs_app.all_tags'))

    return render_template('blogs/add_tag.html', form=form)


@blogs_app.route('/edit-tag/<int:tag_id>/', methods=['GET', 'POST'])
@login_required
@admin_only
def edit_tag(tag_id):
    tag = Tag.query.filter_by(id=tag_id).one()
    tag_color = f'#{tag.color}'
    form = TagForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            tag.name = form.name.data
            tag.color = form.color.data[1:]
            db.session.commit()
            flash('The tag has been successfully updated.', category='info')
            return redirect(url_for('blogs_app.all_tags'))

    return render_template('blogs/edit_tag.html', tag=tag, form=form, tag_color=tag_color)


@blogs_app.route('/delete-tag/<int:tag_id>/', methods=['GET', 'POST'])
@login_required
@admin_only
def delete_tag(tag_id):
    tag = Tag.query.filter_by(id=tag_id).one()
    if request.method == 'POST':
        db.session.delete(tag)
        db.session.commit()
        return redirect(url_for('blogs_app.all_tags'))

    return render_template('blogs/delete_tag.html', tag=tag)


@blogs_app.route('/add-bookmark/<int:blog_id>/', methods=['GET', 'POST'])
@login_required
def add_bookmark(blog_id):
    blog = Blog.query.filter_by(id=blog_id).first_or_404()
    current_user.bookmarks.append(blog)
    db.session.commit()
    flash('The blog has been added to your bookmarks.', category='info')
    return redirect(url_for('main_app.home'))


@blogs_app.route('/delete-bookmark/<int:blog_id>/', methods=['GET', 'POST'])
@login_required
def delete_bookmark(blog_id):
    blog = Blog.query.filter_by(id=blog_id).first_or_404()
    current_user.bookmarks.remove(blog)
    db.session.commit()
    flash('The blog has been removed from your bookmarks.', category='danger')
    if 'bookmarks' in request.referrer:
        return redirect(url_for('blogs_app.get_bookmarks'))
    return redirect(url_for('main_app.home'))


@blogs_app.route('/bookmarks/')
@login_required
def get_bookmarks():
    all_bookmarks = current_user.bookmarks.paginate(per_page=10)
    return render_template('blogs/bookmarks.html', all_bookmarks=all_bookmarks)

lesson_5/blog_project/templates/blogs/add_blog.html
{% extends 'base.html' %}

{% block title %}Add a new blog{% endblock %}

{% block content %}

    <div class="container content">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                {% if 'user' in request.referrer %}
                    <a href="{{ url_for('accounts_app.get_user_profile', user_id=user.id) }}" class="btn btn-danger mt-4 mb-3">
                        <i class="fa-solid fa-angle-left"></i>
                        Go back
                    </a>
                {% else %}
                    <a href="{{ url_for('main_app.home') }}" class="btn btn-danger mt-4 mb-3">
                        <i class="fa-solid fa-angle-left"></i>
                        Go back
                    </a>
                {% endif %}
                <h1 class="text-center text-white">Add a new blog</h1>
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <form method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.title.label(class='form-label text-white') }}
                        {{ form.title(id='title', class='form-control') }}
                    </div>
                    <label for="text" class="form-label text-white">Text</label>
                    <div class="mb-3">
                        {{ form.text }}
                    </div>
                    {{ form.tags.label(class='form-label text-white') }}
                    <div class="mb-3">
                        {{ form.tags(id='tags') }}
                    </div>
                    <input type="hidden" name="referrer" value="{{ request.referrer }}">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="col-3"></div>
        </div>
    </div>

{% endblock %}

lesson_5/blog_project/templates/blogs/add_tag.html
{% extends 'base.html' %}

{% block title %}Add a new tag{% endblock %}

{% block content %}

    <div class="container content">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <a href="{{ url_for('blogs_app.all_tags') }}" class="btn btn-danger mt-4 mb-3">
                    <i class="fa-solid fa-angle-left"></i>
                    Go back
                </a>
                <h1 class="text-center text-white">Add a new tag</h1>
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <form method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.name.label(class='form-label text-white') }}
                        {{ form.name(id='name', class='form-control') }}
                    </div>
                    <div class="mb-3">
                        {{ form.color.label(class='form-label text-white') }}
                        {{ form.color(id='name', type='color', value='#ff0000') }}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="col-4"></div>
        </div>
    </div>

{% endblock %}

lesson_5/blog_project/templates/blogs/all_tags.html
{% extends 'base.html' %}

{% block title %}All tags{% endblock %}

{% block content %}

    <div class="container content">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <a href="{{ url_for('main_app.home') }}" class="btn btn-danger mt-4 mb-3">
                    <i class="fa-solid fa-angle-left"></i>
                    Go back
                </a>
                {% include 'includes/messages.html' %}
                <h1 class="text-center text-white">All tags</h1>
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <div class="text-center pb-3">
                    <a href="{{ url_for('blogs_app.add_tag') }}" class="btn btn-success m-2">
                        <i class="fa-solid fa-tag"></i>  Add a new tag
                    </a>
                </div>
                {% for tag in tags %}
                    <div class="py-2">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">{{ tag.name }}</h4>
                                <a href="{{ url_for('blogs_app.edit_tag', tag_id=tag.id) }}" class="btn btn-primary">
                                    <i class="fa-solid fa-pen-to-square"></i>  Edit
                                </a>
                                <a href="{{ url_for('blogs_app.delete_tag', tag_id=tag.id) }}" class="btn btn-danger">
                                    <i class="fa-solid fa-xmark"></i>  Delete
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-4"></div>
        </div>
    </div>

{% endblock %}

lesson_5/blog_project/templates/blogs/bookmarks.html
{% extends 'base.html' %}

{% block title %}Bookmarks{% endblock %}

{% block content %}

    <div class="container content">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="mt-4">
                    {% include 'includes/messages.html' %}
                </div>
                <h1 class="text-center pt-4 pb-4 text-white">Bookmarks</h1>
                {% if all_bookmarks.items %}
                    {% for blog in all_bookmarks.items %}
                        <div class="py-2">
                            <div class="card">
                                <div class="card-header">
                                    <div class="row">
                                        <div class="col-6">
                                            <a href="{{ url_for('accounts_app.get_user_profile', user_id=blog.user_id) }}"
                                               class="mb-0 h5">
                                                {% if user.id == blog.user_id %}
                                                    <i class="fa-solid fa-user"></i>
                                                {% endif %}
                                                @{{ blog.user.username }}
                                            </a>
                                        </div>
                                        <div class="col-6">
                                            <p class="date mb-0">
                                                <i class="fa-solid fa-calendar-days"></i>
                                                {{ blog.created_at.strftime('%H:%S') }} •
                                                {{ blog.created_at.strftime('%d %b %Y') }}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    {% if blog.tags %}
                                        {% for tag in blog.tags %}
                                            <span class="badge"
                                                  style="background-color: #{{ tag.color }};">{{ tag }}</span>
                                        {% endfor %}
                                    {% endif %}
                                    <h3 class="card-title pt-2">{{ blog.title }}</h3>
                                    <p class="card-text">
                                        {{ blog.text|safe }}
                                    </p>
                                    <a href="{{ url_for('blogs_app.get_blog', blog_id=blog.id) }}"
                                       class="btn btn-success">Details</a>
                                    {% if not blog in user.bookmarks %}
                                        <a href="{{ url_for('blogs_app.add_bookmark', blog_id=blog.id) }}"
                                           class="btn btn-outline-secondary">
                                            <i class="fa-solid fa-star"></i>  Add to bookmarks
                                        </a>
                                    {% else %}
                                        <a href="{{ url_for('blogs_app.delete_bookmark', blog_id=blog.id) }}"
                                           class="btn btn-outline-danger">
                                            <i class="fa-solid fa-star"></i>  Delete from bookmarks
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p class="text-center text-white">You have not added blogs to bookmarks yet.</p>
                {% endif %}
                {% if all_bookmarks.pages > 1 %}
                    <nav>
                        <ul class="pagination justify-content-center mt-4">
                            {% if all_bookmarks.has_prev %}
                                <li class="page-item">
                                    <a class="page-link"
                                       href="{{ url_for('blogs_app.get_bookmarks', page=all_bookmarks.prev_num) }}">
                                        Previous
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item"><a class="page-link btn disabled" href="#">Previous</a></li>
                            {% endif %}
                            {% for page_num in all_bookmarks.iter_pages() %}
                                <li class="page-item {% if page_num == all_bookmarks.page %}active{% endif %}">
                                    <a class="page-link" href="{{ url_for('blogs_app.get_bookmarks', page=page_num) }}">
                                        {{ page_num }}
                                    </a>
                                </li>
                            {% endfor %}
                            {% if all_bookmarks.has_next %}
                                <li class="page-item">
                                    <a class="page-link"
                                       href="{{ url_for('blogs_app.get_bookmarks', page=all_bookmarks.next_num) }}">
                                        Next
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item"><a class="page-link btn disabled" href="#">Next</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
            <div class="col-2"></div>
        </div>
    </div>

{% endblock %}

lesson_5/blog_project/templates/blogs/get_blog.html
{% extends 'base.html' %}

{% block title %}{{ blog.title }}{% endblock %}

{% block content %}

    <div class="container content">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                {% if 'user' in request.referrer %}
                    <a href="{{ url_for('accounts_app.get_user_profile', user_id=user.id) }}" class="btn btn-danger mt-4 mb-3">
                        <i class="fa-solid fa-angle-left"></i>
                        Go back
                    </a>
                {% elif 'bookmarks' in request.referrer %}
                    <a href="{{ url_for('blogs_app.bookmarks') }}" class="btn btn-danger mt-4 mb-3">
                        <i class="fa-solid fa-angle-left"></i>
                        Go back
                    </a>
                {% else %}
                    <a href="{{ url_for('main_app.home') }}" class="btn btn-danger mt-4 mb-3">
                        <i class="fa-solid fa-angle-left"></i>
                        Go back
                    </a>
                {% endif %}
                <div class="py-2">
                    {% include 'includes/messages.html' %}
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-6">
                                    <a href="{{ url_for('accounts_app.get_user_profile', user_id=blog.user_id) }}" class="mb-0 h5">
                                        @{{ blog.user.username }}
                                    </a>
                                </div>
                                <div class="col-6">
                                    <p class="date mb-0">
                                        <i class="fa-solid fa-calendar-days"></i>
                                        {{ blog.created_at.strftime('%H:%M') }} •
                                        {{ blog.created_at.strftime('%d %b %Y') }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            {% if blog.tags %}
                                {% for tag in blog.tags %}
                                    <span class="badge" style="background-color: #{{ tag.color }};">{{ tag }}</span>
                                {% endfor %}
                            {% endif %}
                            {% if user.id == blog.user_id %}
                                <a href="{{ url_for('blogs_app.edit_blog', blog_id=blog.id) }}" class="btn btn-primary float-end">
                                    <i class="fa-solid fa-pen-to-square"></i>  Edit blog
                                </a>
                            {% endif %}
                            <h3 class="card-title pt-2">{{ blog.title }}</h3>
                            <p class="card-text">
                                {{ blog.text|safe }}
                            </p>
                            <hr>
                        </div>
                        <div>
                            <form method="post" action="{{ url_for('blogs_app.get_blog', blog_id=blog.id) }}" class="row g-3">
                                {{ form.hidden_tag() }}
                                <div class="col-8" style="padding-left: 25px;">
                                    <label for="inputComment" class="visually-hidden">Comment</label>
                                    <input type="text" class="form-control" id="inputComment" placeholder="Comment"
                                           name="text">
                                    {% if form.text.errors %}
                                        <ul class="errors py-2">
                                            {% for error in form.text.errors %}
                                                <li class="text-danger">{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                </div>
                                <div class="col-auto">
                                    <button type="submit" class="btn btn-primary mb-3">Add</button>
                                </div>
                            </form>
                            {% for comment in comments %}
                                <div class="px-3">
                                    <p class="h6">@{{ comment.user.username }}<small><span
                                            class="text-secondary">  •  {{ comment.created_at.strftime('%H:%M %d %b %Y') }}</span></small></p>
                                    <p>{{ comment.text }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-2"></div>
        </div>
    </div>

{% endblock %}

lesson_5/blog_project/templates/blogs/search.html
{% extends 'base.html' %}

{% block title %}Search results{% endblock %}

{% block content %}

    <div class="container content">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="mt-4">
                    {% include 'includes/messages.html' %}
                </div>
                <h1 class="text-center pt-4 pb-4 text-white">Search results for "{{ keyword }}"</h1>
                {% if data %}
                    {% if data.total > 0 %}
                        {% if select == 'blogs' %}
                            <h3 class="text-center text-white">Found blogs:</h3>
                            {% for blog in data.items %}
                                <div class="py-2">
                                    <div class="card">
                                        <div class="card-header">
                                            <div class="row">
                                                <div class="col-6">
                                                    <a href="{{ url_for('accounts_app.get_user_profile', user_id=blog.user_id) }}"
                                                       class="mb-0 h5">
                                                        {% if user.id == blog.user_id %}
                                                            <i class="fa-solid fa-user"></i>
                                                        {% endif %}
                                                        @{{ blog.user.username }}
                                                    </a>
                                                </div>
                                                <div class="col-6">
                                                    <p class="date mb-0">
                                                        <i class="fa-solid fa-calendar-days"></i>
                                                        {{ blog.created_at.strftime('%H:%S') }} •
                                                        {{ blog.created_at.strftime('%d %b %Y') }}
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card-body">
                                            {% if blog.tags %}
                                                {% for tag in blog.tags %}
                                                    <span class="badge"
                                                          style="background-color: #{{ tag.color }};">{{ tag }}</span>
                                                {% endfor %}
                                            {% endif %}
                                            <h3 class="card-title pt-2">{{ blog.title }}</h3>
                                            <p class="card-text">
                                                {{ blog.text|safe }}
                                            </p>
                                            <a href="{{ url_for('blogs_app.get_blog', blog_id=blog.id) }}"
                                               class="btn btn-success">Details</a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <h3 class="text-center text-white">Found users:</h3>
                            {% for user in data.items %}
                                <h4>
                                    <i class="fa-solid fa-user text-white"></i>
                                    <a href="{{ url_for('accounts_app.get_user_profile', user_id=user.id) }}" class="text-white">
                                         {{ user.username }}
                                        <span class="fw-light">
                                            {% if user.first_name and user.last_name %}
                                                ({{ user.first_name }} {{ user.first_name }})
                                            {% elif user.first_name %}
                                                ({{ user.first_name }})
                                            {% elif user.last_name %}
                                                ({{ user.last_name }})
                                            {% endif %}
                                        </span>
                                    </a>
                                </h4>
                            {% endfor %}
                        {% endif %}
                        {% if data.pages > 1 %}
                            <nav>
                                <ul class="pagination justify-content-center mt-4">
                                    {% if data.has_prev %}
                                        <li class="page-item">
                                            <a class="page-link"
                                               href="{{ url_for('blogs_app.search_blogs', page=data.prev_num) }}&select={{ select }}&keyword={{ keyword }}">
                                                Previous
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link btn disabled" href="#">Previous</a>
                                        </li>
                                    {% endif %}
                                    {% for page_num in data.iter_pages() %}
                                        <li class="page-item {% if page_num == data.page %}active{% endif %}">
                                            <a class="page-link"
                                               href="{{ url_for('blogs_app.search_blogs', page=page_num) }}&select={{ select }}&keyword={{ keyword }}">
                                                {{ page_num }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                    {% if data.has_next %}
                                        <li class="page-item">
                                            <a class="page-link"
                                               href="{{ url_for('blogs_app.search_blogs', page=data.next_num) }}&select={{ select }}&keyword={{ keyword }}">
                                                Next
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link btn disabled" href="#">Next</a></li>
                                    {% endif %}
                                </ul>
                            </nav>
                        {% endif %}
                    {% else %}
                        <p class="text-center text-white">Nothing found</p>
                    {% endif %}
                {% else %}
                    <p class="text-center text-white">Nothing found</p>
                {% endif %}
            </div>
            <div class="col-2"></div>
        </div>
    </div>

{% endblock %}