lesson_7/accounts/api/urls.py
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()

router.register(r'user', views.UserViewSet)

app_name = 'accounts_api'

urlpatterns = router.urls

lesson_7/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views
from .forms import CustomAuthenticationForm

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='login.html',
        authentication_form=CustomAuthenticationForm,
        redirect_authenticated_user=True),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('signup/', views.SignupPageView.as_view(), name='signup'),
    path(
        'reset-password/',
        auth_views.PasswordResetView.as_view(
            template_name='reset_password.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='password_reset_email.html',
        ),
        name='reset_password',
    ),
    path(
        'reset-password-sent/',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_form.html',
            success_url=reverse_lazy('accounts:password_reset_complete')
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset-password-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'),
        name='password_reset_complete',
    ),
    path('activate/<uidb64>/<token>/', views.activate_account, name='activate_account'),
    path('resend-link/<email>/', views.resend_activation_link, name='resend_activation_link'),
]

lesson_7/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.authtoken.views import obtain_auth_token
from graphene_django.views import GraphQLView

from config.settings import DEBUG
from config.api.views import APIRootView
from onlineschool.views import HomeTemplateView, Contact, APITemplateView, generate_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', HomeTemplateView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('courses/', include('onlineschool.urls')),
    path('contact/', Contact.as_view(), name='contact'),
    path('api-token/', APITemplateView.as_view(), name='api_token'),
    path('generate-token/', generate_token, name='generate_token'),

    # Rest Framework
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token),
    path('api/v1/', APIRootView.as_view(), name='api_root_view'),
    path('api/v1/', include('onlineschool.api.urls')),
    path('api/v1/', include('accounts.api.urls')),

    # GraphQL
    path('graphql/', GraphQLView.as_view()),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]
    urlpatterns.insert(0, path('graphql/', GraphQLView.as_view(graphiql=True)))

lesson_7/onlineschool/api/urls.py
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()

router.register(r'course', views.CourseViewSet)
router.register(r'schedule', views.ScheduleViewSet)
router.register(r'category', views.CategoryViewSet)
router.register(r'teacher', views.TeacherViewSet)
router.register(r'student', views.StudentViewSet)
router.register(r'registration-request', views.RegistrationRequestViewSet)
router.register(r'course-request', views.CourseRequestViewSet)
router.register(r'student-courses', views.StudentCoursesViewSet, basename='student_courses')

app_name = 'onlineschool_api'

urlpatterns = router.urls

lesson_7/onlineschool/urls.py
from django.urls import path

from . import views

app_name = 'onlineschool'

urlpatterns = [
    path('', views.CourseListView.as_view(), name='courses'),
    path('search/', views.SearchCourseListView.as_view(), name='search'),
    path('schedule/', views.ScheduleListView.as_view(), name='schedule'),
    path('schedule-calendar/', views.ScheduleCalendarView.as_view(), name='schedule_calendar'),
    path('schedule-calendar-nav/', views.get_month_ajax, name='schedule_calendar_nav'),
    path('create-course/', views.CourseCreateView.as_view(), name='create_course'),
    path('update-course/<slug:course_slug>/', views.CourseUpdateView.as_view(), name='update_course'),
    path('delete-course/<slug:course_slug>/', views.CourseDeleteView.as_view(), name='delete_course'),
    path('create-category/', views.CategoryCreateView.as_view(), name='create_category'),
    path('update-category/<slug:category_slug>/', views.CategoryUpdateView.as_view(), name='update_category'),
    path('delete-category/<slug:category_slug>/', views.CategoryDeleteView.as_view(), name='delete_category'),
    path('create-group/', views.GroupCreateView.as_view(), name='create_group'),
    path('update-group/<slug:group_slug>/', views.GroupUpdateView.as_view(), name='update_group'),
    path('delete-group/<slug:group_slug>/', views.GroupDeleteView.as_view(), name='delete_group'),
    path('my-courses/', views.StudentCoursesListView.as_view(), name='student_courses'),
    path('category/<slug:category_slug>/', views.CourseByCategoryListView.as_view(), name='course_by_category'),
    path('registration-requests/', views.RegistrationRequestListView.as_view(), name='registration_requests'),
    path('delete-request/<int:pk>/', views.RegistrationRequestDeleteView.as_view(), name='delete_request'),
    path('add-to-group/<slug:course_slug>/<int:user_id>/', views.add_student_to_group, name='add_student_to_group'),
    path('<slug:course_slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('<slug:course_slug>/register/', views.register_registration_request, name='register_registration_request'),
    path('<slug:course_slug>/course-request/', views.register_course_request, name='register_course_request'),
    path(
        'send-registration-link/<str:email>/<slug:course_slug>/',
        views.send_registration_link, name='send_registration_link',
    ),
]

lesson_7/onlineschool/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group, Permission
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

from slugify import slugify

User = get_user_model()


class Teacher(models.Model):
    user = models.OneToOneField(User, verbose_name='Пользователь', on_delete=models.CASCADE, unique=True)
    short_bio = models.CharField('Короткая биография/специальность', max_length=64)
    bio = RichTextUploadingField('Биография')

    class Meta:
        verbose_name = 'преподаватель'
        verbose_name_plural = 'Преподаватели'

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        student_exists = Student.objects.filter(user=self.user)
        if student_exists:
            raise ValidationError('Уже существует студент с этим профилем')
        super().save(*args, **kwargs)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь', unique=True)
    wishlist = models.ManyToManyField(
        'Course', verbose_name='Список желаемого', related_name='student_wishlist', blank=True
    )

    class Meta:
        verbose_name = 'студент'
        verbose_name_plural = 'Студенты'

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        teacher_exists = Teacher.objects.filter(user=self.user)
        if teacher_exists:
            raise ValidationError('Уже существует преподаватель с этим профилем')
        super().save(*args, **kwargs)


# Auto create Teacher or Student (one to one) when User is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == '1':
            group = Group.objects.filter(name='Учитель').first()
            if not group:
                group = Group.objects.create(name='Учитель')
                all_models = ['course', 'schedule', 'category', 'registrationrequest', 'courserequest']
                prefixes = ['add', 'change', 'delete', 'view']
                for model in all_models:
                    for prefix in prefixes:
                        try:
                            permission = Permission.objects.get(codename=f'{prefix}_{model}')
                        except Permission.DoesNotExist:
                            print(f'Permission with name "can_{prefix}_{model}" does not exist.')
                            continue
                        group.permissions.add(permission)
            instance.groups.add(group)
            Teacher.objects.create(user=instance)
        else:
            Student.objects.create(user=instance)


class Review(models.Model):
    student = models.ForeignKey(Student, verbose_name='Студент', on_delete=models.CASCADE)
    rating = models.PositiveIntegerField('Оценка', validators=[MinValueValidator(0), MaxValueValidator(5)])
    text = RichTextUploadingField('Описание')

    class Meta:
        verbose_name = 'отзыв'
        verbose_name_plural = 'Отзывы'

    def __str__(self):
        return str(self.student)


class Category(models.Model):
    name = models.CharField('Название', max_length=100)
    color = models.CharField('Цвет', max_length=7, default='#0D6EFD')
    slug = models.SlugField('URL', max_length=150, unique=True)

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            new_slug = slugify(self.name)
            slug_exists = Category.objects.filter(slug=new_slug).exists()
            if slug_exists:
                self.slug = f'{str(new_slug)}-{str(self.id)}'
            else:
                self.slug = new_slug
            self.save()


class Course(models.Model):
    category = models.ForeignKey('Category', verbose_name='Категория', on_delete=models.CASCADE)
    name = models.CharField('Название', max_length=200)
    photo = models.ImageField('Фотография', blank=True, null=True, default='course_default.png')
    duration = models.PositiveIntegerField('Длительность (в мес.)')
    short_description = RichTextUploadingField('Краткое описание', blank=True, null=True)
    description = RichTextUploadingField('Описание')
    teachers = models.ManyToManyField('Teacher', verbose_name='Преподаватели')
    required_knowledge = RichTextUploadingField('Необходимые знания')
    after_course = RichTextUploadingField('После обучения')
    price = models.PositiveIntegerField('Стоимость (в руб.)', blank=True, null=True)
    slug = models.SlugField('URL', max_length=250, unique=True)

    class Meta:
        verbose_name = 'курс'
        verbose_name_plural = 'Курсы'
        ordering = ('-id',)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            new_slug = slugify(self.name)
            slug_exists = Course.objects.filter(slug=new_slug).exists()
            if slug_exists:
                self.slug = f'{str(new_slug)}-{str(self.id)}'
            else:
                self.slug = new_slug
            self.save()


class Schedule(models.Model):
    course = models.ForeignKey(Course, verbose_name='Курс', on_delete=models.CASCADE)
    students = models.ManyToManyField(Student, verbose_name='Студенты', blank=True)
    start_date = models.DateField('Дата старта курса')
    end_date = models.DateField('Дата окончания курса')
    is_announced_later = models.BooleanField('Не показывать дату начала курса?')
    slug = models.SlugField('URL', max_length=250, unique=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            new_slug = slugify(f'{self.course.name}-{self.start_date.month}-{self.start_date.year}')
            slug_exists = Schedule.objects.filter(slug=new_slug).exists()
            if slug_exists:
                self.slug = f'{str(new_slug)}-{str(self.id)}'
            else:
                self.slug = new_slug
            self.save()

    @property
    def get_html_course_url(self):
        url = reverse('onlineschool:course_detail', args=[self.course.slug])
        return f'<a href="{url}"> {self.course.name} </a>'

    class Meta:
        verbose_name = 'расписание'
        verbose_name_plural = 'Расписание'
        ordering = ('is_announced_later', 'start_date')

    def __str__(self):
        return f'{self.course} - {self.start_date}'


class RegistrationBase(models.Model):
    student = models.ForeignKey(Student, verbose_name='Студент', on_delete=models.CASCADE, blank=True, null=True)
    email = models.EmailField('Почта', max_length=32)
    course = models.ForeignKey(Course, verbose_name='Курс', on_delete=models.CASCADE)
    date_created = models.DateField('Дата создания', auto_now_add=True)

    class Meta:
        abstract = True

    def __str__(self):
        return str(self.email)


class RegistrationRequest(RegistrationBase):
    class Meta:
        ordering = ['-date_created']
        verbose_name = 'заявка на запись'
        verbose_name_plural = 'Заявки на запись'


class CourseRequest(RegistrationBase):
    class Meta:
        verbose_name = 'заявка о старте набора'
        verbose_name_plural = 'Заявки о старте набора'

lesson_7/accounts/api/views.py
from rest_framework.viewsets import ModelViewSet

from ..models import User
from .serializers import UserSerializer


class UserViewSet(ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

lesson_7/config/api/views.py
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework.reverse import reverse


class APIRootView(APIView):
    permission_classes = [IsAuthenticatedOrReadOnly]

    def get(self, request):
        return Response({
            'auth': {
                'users': reverse('accounts_api:user-list', request=request),
            },
            'onlineschool': {
                'courses': reverse('onlineschool_api:course-list', request=request),
                'schedule': reverse('onlineschool_api:schedule-list', request=request),
                'categories': reverse('onlineschool_api:category-list', request=request),
                'teachers': reverse('onlineschool_api:teacher-list', request=request),
                'students': reverse('onlineschool_api:student-list', request=request),
            },
            'for-teachers': {
                'registration-requests': reverse('onlineschool_api:registrationrequest-list', request=request),
                'course-requests': reverse('onlineschool_api:courserequest-list', request=request),
            },
            'for-students': {
                'student-courses': reverse('onlineschool_api:student_courses-list', request=request),
            },
        })

lesson_7/templates/api.html
{% extends 'base.html' %}

{% block title %}API{% endblock %}

{% block content %}

    <div class="container my-5">
        {% include 'includes/messages.html' %}
        <h1 class="text-center">API</h1>
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="container mt-5">
                <h2 class="mb-4">
                    <a href="{% url 'api_root_view' %}" target="_blank">
                        {{ request.get_host }}{% url 'api_root_view' %}
                    </a>
                </h2>
                {% if token %}
                    <p>Ваш токен: </p><h5>{{ token }}</h5>
                    <form method="post" action="{% url 'generate_token' %}">
                        {% csrf_token %}
                        <input type="submit" value="Сгенерировать новый токен" class="btn btn-success">
                    </form>
                {% else %}
                    <h5 class="text-danger">У вас нет токена.</h5>
                    <form method="post" action="{% url 'generate_token' %}">
                        {% csrf_token %}
                        <input type="submit" value="Сгенерировать токен" class="btn btn-success">
                    </form>
                {% endif %}
                </div>
            </div>
            <div class="col-2"></div>
        </div>
    </div>

{% endblock %}

lesson_7/templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Ajax -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- Icons -->
    <script src="https://kit.fontawesome.com/148fa55e15.js" crossorigin="anonymous"></script>

    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/spinner.css' %}">

    <title>
        {% block title %}Online School{% endblock %}
    </title>
</head>

<body>

<div class="objects">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Online School</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'onlineschool:courses' %}">
                            Курсы
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'onlineschool:schedule_calendar' %}">
                            Календарь
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'contact' %}">
                            Контакты
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        {% if request.user.user_type == '1' %}
                            <li class="nav-item dropdown align-self-center">
                                <a class="btn btn-sm btn-secondary dropdown-toggle button-margin" href="#"
                                   role="button" id="dropdown_1" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-solid fa-chalkboard-user"></i>  Для преподов
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdown_1">
                                    <li>
                                        <a class="dropdown-item" href="{% url 'onlineschool:create_course' %}">
                                            Добавить курс
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'onlineschool:create_category' %}">
                                            Добавить категорию
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'onlineschool:create_group' %}">
                                            Создать курс с группой
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'onlineschool:schedule' %}">
                                            Расписание
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'onlineschool:registration_requests' %}">
                                            Заявки на запись
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        {% endif %}
                        <li class="nav-item dropdown align-self-center">
                            <a class="btn btn-sm btn-secondary dropdown-toggle" href="#" role="button" id="dropdown_2"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa-solid fa-user"></i>  {{ user.email }}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdown_2">
                                {% if user.user_type == '2' %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'onlineschool:student_courses' %}">
                                            Мои курсы
                                        </a>
                                    </li>
                                {% endif %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'api_token' %}">
                                        API
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                                        Выйти
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <div class="align-self-center">
                            <a href="{% url 'accounts:login' %}" class="btn btn-sm btn-primary button-margin">
                                <i class="fa-solid fa-right-to-bracket"></i>  Войти
                            </a>
                            <a href="{% url 'accounts:signup' %}" class="btn btn-sm btn-success">
                                <i class="fa-solid fa-user-plus"></i>  Зарегистрироваться
                            </a>
                        </div>
                    {% endif %}
                </ul>
                <form method="get" action="{% url 'onlineschool:search' %}" class="d-flex">
                    <input name="keyword" class="form-control form-control-sm me-2" type="search" placeholder="Искать..."
                           aria-label="Search">
                    <button class="btn btn-sm btn-outline-success" type="submit">Поиск</button>
                </form>
            </div>
        </div>
    </nav>

    {% block content %}{% endblock %}

</div>


<section>
    <footer class="text-center">
        <div class="text-center p-3">
            © {% now 'Y' %} Online School
        </div>
    </footer>
    <!-- Footer -->
</section>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script src="{% static 'js/onmouseover.js' %}"></script>
<script src="{% static 'js/calendar_ajax.js' %}"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
</body>

</html>

lesson_7/templates/contact_form.html
{% extends 'base.html' %}

{% block title %}Контакты{% endblock %}

{% block content %}

    <div class="container my-5">
        {% include 'includes/messages.html' %}
        <h1 class="text-center">Связь с нами</h1>
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="container mt-5">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Отправить" class="btn btn-primary">
                    </form>
                </div>
            </div>
            <div class="col-2"></div>
        </div>
    </div>

{% endblock %}

lesson_7/templates/home.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
    <div class="container my-5">
        {% include 'includes/messages.html' %}
        <h1 class="text-center">Добро пожаловать на образовательную платформу!</h1>
        <div class="row pt-3 mt-5">
            <div class="col-4">
                <h4 class="mb-2">Все категории:</h4>
                <a href="{% url 'onlineschool:courses' %}" class="btn btn-outline-dark my-1">
                    Все
                </a><br>
                {% for category in object_list %}
                    <a href="{% url 'onlineschool:course_by_category' category_slug=category.slug %}"
                       class="btn btn-outline-light position-relative my-1"
                       style="color: #1b1b1b; border-color: {{ category.color }};">
                        {{ category.name }}
                        {% if category.course_set.count %}
                            {% if category.course_set.count == 1 %}
                                <span class="badge bg-secondary">1 курс</span>
                            {% elif category.course_set.count > 1 and category.course_set.count < 5 %}
                                <span class="badge bg-secondary">{{ category.course_set.count }} курса</span>
                            {% else %}
                                <span class="badge bg-secondary">{{ category.course_set.count }} курсов</span>
                            {% endif %}
                        {% endif %}
                    </a>
                    {% if request.user.user_type == '1' %}
                        <a href="{% url 'onlineschool:update_category' category_slug=category.slug %}"
                           class="badge bg-success" style="text-decoration: none;" >
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>
                        <a href="{% url 'onlineschool:delete_category' category_slug=category.slug %}"
                           class="badge bg-danger" style="text-decoration: none;" >
                            <i class="fa-solid fa-trash-can"></i>
                        </a>
                    {% endif %}
                    <br>
                {% endfor %}
            </div>
            <div class="col-8">
                <div>
                    <h4 class="mb-2 left">Курсы в этом месяце:</h4>
                    <a href="{% url 'onlineschool:schedule_calendar' %}" class="btn btn-primary right mb-2">
                        <i class="fa-solid fa-calendar-days"></i>
                          Весь календарь
                    </a>
                </div>
                {{ calendar }}
            </div>
        </div>
    </div>
{% endblock %}

lesson_7/templates/search_course.html
{% extends 'base.html' %}

{% block title %}Поиск{% endblock %}

{% block content %}

    <div class="container my-5">
        <div class="row">
            {% include 'includes/messages.html' %}
            <h1 class="text-center">Поиск</h1>
            {% for course in object_list %}
                <div class="card m-2" style="width: 18rem;">
                    <img src="{{ course.photo.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <span class="badge" style="background-color: {{ course.category.color }};">
                            {{ course.category.name }}
                        </span>
                        <h5 class="card-title my-3">{{ course.name }}</h5>
                        <p class="card-text mb-0">
                            <i class="fa-solid fa-arrow-rotate-right"></i> Длительность - {{ course.duration }} мес.
                        </p>
                        {% for schedule in course.schedule_set.all %}
                            {% if forloop.first %}
                                {% if not schedule.is_announced_later %}
                                    <p class="card-text mb-0">
                                        <i class="fa-solid fa-calendar-days"></i> с {{ schedule.start_date }}
                                    </p>
                                {% else %}
                                    <p class="card-text mb-0">
                                        <i class="fa-solid fa-calendar-days"></i> о дате старта будет объявлено позже
                                    </p>
                                {% endif %}
                            {% endif %}
                            {% empty %}
                            <p class="card-text mb-0">
                                <i class="fa-solid fa-calendar-days"></i> в ближайшее время не планируется
                            </p>
                        {% endfor %}
                        <a href="{% url 'onlineschool:course_detail' course_slug=course.slug %}"
                           class="btn btn-primary mt-3">
                            Подробнее
                        </a>
                    </div>
                </div>
            {% empty %}
                <div class="text-center">
                    <h5>Ничего не найдено</h5>
                    <a href="{% url 'home' %}" class="btn btn-primary">На главную</a>
                </div>
            {% endfor %}
        </div>
        {% include 'includes/paginator.html' %}
    </div>

{% endblock %}